name: Deploy to EC2

on:
  push:
    branches: [ main ] # or your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use your React.js version requirement

    - name: Install dependencies and build
      run: |
        npm install
        npm run build
        
    - name: Deploy to EC2
        run: echo "admin123"
        run: echo ${{ secrets.EC2_HOST }} ${{ secrets.EC2_USERNAME }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/"
        target: "/var/www/my-react-app"
        
    - name: Restart Nginx (optional)
        run: echo ${{ secrets.EC2_HOST }} ${{ secrets.EC2_USERNAME }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl restart nginx